olympus:
  ares:
    initiative-defense: true
    passive-defense: true
    passive-defense-config:
      xss-defense: false
      over-times-fusing: false
      over-times-fusing-interceptor-config:
        threshold: 3
        time-millis-per-slice: 1000
        window-size: 10