olympus:
  ares:
    initiative-defense: true
    passive-defense: true
    passive-defense-config:
      xss-defense: true
      over-times-fusing: true
      over-times-fusing-interceptor-config:
        threshold: 10
        time-millis-per-slice: 1000
        window-size: 15